name: BS
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:



  
jobs:
  main:
    name: Build and Validate
    runs-on: ubuntu-20.04

    permissions:
      contents: write
    strategy:
      max-parallel: 1
      matrix:
        include:
          - source: specs/log.bs
            destination: ../log.html

    
    steps:
      - uses: actions/checkout@v4
      - uses: w3c/spec-prod@v2
        with:
          TOOLCHAIN: bikeshed
          SOURCE: ${{ matrix.source }}
          DESTINATION: ${{ matrix.destination }}
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
